### ISSUE TITLE
GitHub Actions are not up-to-date

### ISSUE THREAD

**Issue by ludovicm67** [openlayers-elements/openlayers-elements#102]
Right now, the CI is failing because of the use of deprecated/unsupported GitHub Action versions.

Things that needs to be done:

- [x] Upgrade each GitHub Action to the latest major version available
- [x] Upgrade the Node.js version that is used to use the latest LTS version, which is 20 as of today
- [x] Replace the use of `@master` version with the latest available major version (`@vX`) for all actions that are still using it
- [x] Remove the use of `nelonoel/branch-name` to use something like described here: https://stackoverflow.com/a/58035262

**Comment by ktk** [comment]
Just a FYI I talk to someone that is using these components and upgraded them in a fork, see https://github.com/spwoodcock/openlayers-elements

He asked if we would be interested in merging & I proposed that we have a discussion on how to governance the components. It might be that we move them to an independent github org so others can easier contribute as well. So we should finish those discussions before we work on the code again.

**Comment by ludovicm67** [comment]
Done!
