### ISSUE TITLE
Hot-reloading for Vite dev server

### ISSUE THREAD

**Issue by spwoodcock** [openlayers-elements/openlayers-elements#124]
### Issue

- Currently we use `npm run start`, which uses `vite` to run the dev server.
- A `prestart` script is used to run `tsc` so that TS modules are compiled to JS before the server starts.
- Ideally we would have hot-reloading, so that changes to the components would reflect on the running demo page.

### Possible Solutions

1. Ideally the Vite configuration can handle this somehow. I assume it's not picking up the `.ts` files as the `.js` files are referenced everywhere.
2. A package like `npm-run-all` or `concurrently` (or `pnpm`) to run multiple scripts at once.
  a. We could have a script to run `tsc --watch` and another for `vite` to run together.
3. Something else!

**Comment by tpluscode** [comment]
Vite itself does not require compilation. The problem is Polymer analyser which only understands JS. 

> Something else!

I'm 90% complete replacing that whole setup with Storybook.

**Comment by spwoodcock** [comment]
Nice, sounds ideal!
